package com.example.thirtydaysoffitness.model

import com.example.thirtydaysoffitness.R

object FitnessRepository {
    val fit = listOf<Fitness>(
        Fitness(
            R.string.day_1,
            R.string.pushups,
            R.string.pushups_sets_and_reps,
            R.string.pushups_description,
            R.drawable.pushup2
        ),
        Fitness(
            R.string.day_2,
            R.string.lunges,
            R.string.lunges_sets_and_reps,
            R.string.lunges_description,
            R.drawable.rlunges
        ),
        Fitness(
            R.string.day_3,
            R.string.squats,
            R.string.squats_sets_and_reps,
            R.string.squats_description,
            R.drawable.squatt
        ),
        Fitness(
            R.string.day_4,
            R.string.plank,
            R.string.plank_sets_and_reps,
            R.string.plank_description,
            R.drawable.planks
        ),

        Fitness(
            R.string.day_5,
            R.string.burpees,
            R.string.burpees_sets_and_reps,
            R.string.burpees_description,
            R.drawable.burpe
        ),
        Fitness(
            R.string.day_6,
            R.string.pullups,
            R.string.pulldown_sets_and_reps,
            R.string.pullups_description,
            R.drawable.pullu
        ),
        Fitness(
            R.string.day_7,
            R.string.situps,
            R.string.situps_sets_and_reps,
            R.string.situps_description,
            R.drawable.situ
        ),
        Fitness(
            R.string.day_8,
            R.string.jumping_jacks,
            R.string.jumping_jacks_sets_and_reps,
            R.string.jumping_jacks_description,
            R.drawable.jumpingj
        ),
        Fitness(
            R.string.day_9,
            R.string.dips,
            R.string.dips_sets_and_reps,
            R.string.dips_description,
            R.drawable.tricepdips
        ),
        Fitness(
            R.string.day_10,
            R.string.leg_raises,
            R.string.leg_raises_sets_and_reps,
            R.string.leg_raises_description,
            R.drawable.legri
        ),
        Fitness(
            R.string.day_11,
            R.string.box_jumps,
            R.string.box_jumps_sets_and_reps,
            R.string.box_jumps_description,
            R.drawable.boxj
        ),
        Fitness(
            R.string.day_12,
            R.string.rowing_machine,
            R.string.rowing_machine_sets_and_reps,
            R.string.rowing_machine_description,
            R.drawable.row
        ),
        Fitness(
            R.string.day_13,
            R.string.medicine_ball_slams,
            R.string.medicine_ball_slams_sets_and_reps,
            R.string.medicine_ball_slams_description,
            R.drawable.ballslam
        ),
        Fitness(
            R.string.day_14,
            R.string.russian_twists,
            R.string.russian_twists_sets_and_reps,
            R.string.russian_twists_description,
            R.drawable.rusiantwist
        ),
        Fitness(
            R.string.day_15,
            R.string.shoulder_press,
            R.string.shoulder_press_sets_and_reps,
            R.string.shoulder_press_description,
            R.drawable.shoulderpress
        ),
        Fitness(
            R.string.day_16,
            R.string.jump_rope,
            R.string.jump_rope_sets_and_reps,
            R.string.jump_rope_description,
            R.drawable.jumprope
        ),
        Fitness(
            R.string.day_17,
            R.string.deadlifts,
            R.string.deadlifts_sets_and_reps,
            R.string.deadlifts_description,
            R.drawable.deadlist
        ),
        Fitness(
            R.string.day_18,
            R.string.cyclist,
            R.string.calf_raise_sets_and_reps,
            R.string.cyclist_description,
            R.drawable.cyclist
        ),
        Fitness(
            R.string.day_19,
            R.string.step_ups,
            R.string.step_ups_sets_and_reps,
            R.string.step_ups_description,
            R.drawable.stepup
        ),
        Fitness(
            R.string.day_20,
            R.string.tricep_dips,
            R.string.treadmill_sets_and_reps,
            R.string.tricep_dips_description,
            R.drawable.legr
        ),
        Fitness(
            R.string.day_21,
            R.string.hanging_leg_raises,
            R.string.hanging_leg_raises_sets_and_reps,
            R.string.hanging_leg_raises_description,
            R.drawable.legri
        ),
        Fitness(
            R.string.day_22,
            R.string.treadmill,
            R.string.treadmill_sets_and_reps,
            R.string.treadmill_description,
            R.drawable.treadmill
        ),
        Fitness(
            R.string.day_23,
            R.string.dumbbell_rows,
            R.string.dumbbell_rows_sets_and_reps,
            R.string.dumbbell_rows_description,
            R.drawable.dumbellrows
        ),
        Fitness(
            R.string.day_24,
            R.string.incline_press,
            R.string.incline_press_sets_and_reps,
            R.string.incline_press_description,
            R.drawable.benchpress
        ),
        Fitness(
            R.string.day_25,
            R.string.pulldown,
            R.string.pullups_sets_and_reps,
            R.string.pulldown_description,
            R.drawable.latpulldown
        ),
        Fitness(
            R.string.day_26,
            R.string.leg_press,
            R.string.leg_press_sets_and_reps,
            R.string.leg_press_description,
            R.drawable.legpress
        ),
        Fitness(
            R.string.day_27,
            R.string.lateral_raise,
            R.string.lateral_raise_sets_and_reps,
            R.string.lateral_raise_description,
            R.drawable.latraise
        ),
        Fitness(
            R.string.day_28,
            R.string.calf_raise,
            R.string.calf_raise_sets_and_reps,
            R.string.calf_raise_description,
            R.drawable.calfraises
        ),
        Fitness(
            R.string.day_29,
            R.string.barbell_curl,
            R.string.barbell_curl_sets_and_reps,
            R.string.barbell_curl_description,
            R.drawable.barbellcurl
        ),
        Fitness(
            R.string.day_30,
            R.string.lat_pulldown,
            R.string.lat_pulldown_sets_and_reps,
            R.string.lat_pulldown_description,
            R.drawable.latpulldown
        ),

    )
}